### ISSUE TITLE
Meet panic when use this abstract

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2642]
### Bug description

I'm updating code from 0.19 to 0.27.

This is minimal code.

```ts

export interface ISerialize {
    serialize<__R, __S extends CoreSerializer<__R>>(serializer: __S): __R;
}

export abstract class CoreSerializer<R> {
    // omit ..
}

export abstract class Serializer<R> extends CoreSerializer<R> {
    // omit ..
}

export class ScaleSerializer extends Serializer<string>{
    // omit ..
    serializeClass<C extends ISerialize>(value: C): string {
        value.serialize<string, this>(this);
        return "";
    }
}
```
it works in 0.19.

<del>But now meet panic in 0.27. </del>

Now it will meet syntax error.

### Steps to reproduce

asc ./index.ts

### AssemblyScript version

0.27

**Comment by yjhmelody** [comment]
Sorry, could not reproducer this error by this mininal code.


ERROR TS2339: Property 'serialize' does not exist on type '~lib/object/Object'.
     :
 161 │ value.serialize<BytesBuffer, this>(this);
     │       ~~~~~~~~~
     └─ in assembly/serializer.ts(161,15)

FAILURE 1 compile error(s)

**Comment by MaxGraey** [comment]
Perhaps it's similar to #2618 issue with `this` type?

**Comment by yjhmelody** [comment]
Maybe I made a mistake, it's been a long time, and it's hard to reproduce now
