### ISSUE TITLE
Cannot find module 'assemblyscript/asc' or its corresponding type declarations.

### ISSUE THREAD

**Issue by bbrk24** [AssemblyScript/assemblyscript#2241]
The website says it's possible to call `asc` programmatically in JavaScript, and can be imported as follows:

> ```js
> import asc from "assemblyscript/asc";
> ```

Source: [Programmatic usage](https://www.assemblyscript.org/compiler.html#programmatic-usage)

However, trying to do so in TypeScript fails with the error message from the title. There is no `@types/assemblyscript` package either, at least not that yarn can find.

TypeScript seems to think the module is called `assemblyscript/dist/asc`, as I can import that with no such error.

**Comment by bbrk24** [comment]
If I ignore the errors and run it in JavaScript anyways, Node gives me the error `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './asc' is not defined by "exports" in C:\Users\[...]\node_modules\assemblyscript\package.json`. I tried it in Node v16 and v17, but they both give me the same error. However, I definitely see it in the `package.json`, so I'm not really sure what's up.

**Comment by dcodeIO** [comment]
This is a relatively recent change (in v0.20). What's the version of the compiler you are using?

**Comment by bbrk24** [comment]
@dcodeIO I have version 0.20.2 installed.

**Comment by dcodeIO** [comment]
Toying around with this a little, seems the import can be resolved when adding `"moduleResolution": "NodeNext"` to tsconfig.json. However, there's a new error then on

```ts
import asc from "assemblyscript/asc";
```

stating

```
Module 'assemblyscript/asc' cannot be imported using this construct. The specifier only resolves
to an ES module, which cannot be imported synchronously. Use dynamic import instead.ts(1471)
```

which seems just as odd, as it doesn't go away even when adding `"target": "ESNext"` and `"module": "NodeNext"`.

There is another hint, however, stating

```
Compiler option 'module' of value 'nodenext' is unstable. Use nightly TypeScript to silence this error.
Try updating with 'npm install -D typescript@next'.ts
```

which I haven't tested. Perhaps it's simply not supported by stable TS yet?

**Comment by bbrk24** [comment]
That's unfortunate. I didn't realize it was ESM-only; I'm using CommonJS for imports, so that's probably why it's broken.

**Comment by bbrk24** [comment]
@dcodeIO I got it to work in TypeScript 4.5.5 by using `--module ES2022 --moduleResolution node`, but I have to import `assemblyscript/dist/asc.js` rather than just `assemblyscript/asc`.

**Comment by bbrk24** [comment]
I am seeing very strange behavior when I do this. For example, the following code logs out several megabytes, mostly base-64-encoded data:

```js
import asc from "assemblyscript/dist/asc.js";
throw new Error();
```

**Comment by dcodeIO** [comment]
I believe that's because Node.js by default doesn't load source maps, and somehow believes that printing all minified code on the same line is of great use. Providing `--enable-source-maps` to the Node.js invocation should yield a proper error.

**Comment by bbrk24** [comment]
Yep, `--enable-source-maps` helped. Still, the original issue (that I have to use a different import path than documented) stands.

**Comment by dcodeIO** [comment]
My intuition here is that, when it works in plain JS, this would be an incompatibility of TS with Node's new `exports` field. Would assume that the TS folks are already working on it, but hard to say for sure. Does it perhaps work with `typescript@next`, as the warning above recommends?

**Comment by bbrk24** [comment]
@dcodeIO No, but I currently can't compile anything with `typescript@next`, due to a compilation error in node_modules/typescript/lib/typescript.d.ts.

**Comment by jerrygreen** [comment]
Before trying Typescript just try to import it from js. I'm getting `Cannot find module` error with just pure js.
At least I'm using `v14.15.2`, but you seem to stuck into the same error with v16-17, too, so I guess it's not the Node version.

**Comment by bbrk24** [comment]
@jerrygreen I couldn't import it from the Node REPL or a commonjs script. I had to either save it as a `.mjs` file or put `"type": "module"` in package.json. Even then, I'm using Node 17.

**Comment by jerrygreen** [comment]
I have `type: module` in package json but this doesn't resolve the problem

**Comment by 0xbe1** [comment]
> This is a relatively recent change (in v0.20). What's the version of the compiler you are using?

I downgrade to 0.19.23 and it works

**Comment by piotr-oles** [comment]
I tried to update to the newest assemblyscript in the as-loader library (a webpack loader for assemblyscript). Unfortunately, ESM doesn't work well with webpack... Would it be possible to provide a CJS format too? I feel like the node environment is not fully ready for the switch to ESM.

**Comment by Upperfoot** [comment]
This is still an issue

**Comment by ufReitter** [comment]
After spending the whole day refactoring my nestjs backend to use ESM modules I had at first no luck.
Still got this error in the editor and tsc compiler.

Finally just supressing the error with:

// @ts-ignore
import asc from 'assemblyscript/asc';

did the trick.

The latest version of the ASC compiler works fine now in my backend.

Besides 
  "type": "module",
in the package.json
I use these 
  "compilerOptions": {
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "strictPropertyInitialization": false,
    "esModuleInterop": true,
    "baseUrl": "./",
    "outDir": "./dist",
    "target": "es2020",
    "lib": ["es2020", "DOM"],
    "module": "ES2020",
    "moduleResolution": "Node",
    "strict": true,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true
  },

**Comment by bbrk24** [comment]
I don't like to use `@ts-ignore` or `@ts-expect-error`, but I see why that may be necessary here.

**Comment by jerrygreen** [comment]
Actually the issue is not an issue if all those requirements are met:

1. You use `import asc from 'assemblyscript/dist/asc.js'` instead of `import asc from 'assemblyscript/asc.js'`
2. assemblyscript v0.20.3 (newer version might fit as well)
3. Node v16 (I have Node v16.14.2, whereas Node v14 doesn't work)
4. `"type": "module"` in package.json

Break any of it and you gonna have a bad time :(

**Comment by piotr-oles** [comment]
Yep - especially when you build a package for another tool that didn't migrate to ESM :/ I cannot use new bindings stuff for the as-loader for webpack, because webpack doesn't support ESM
