### ISSUE TITLE
as-wasi fails to build with v0.20.0

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#2259]
This feels related to https://github.com/AssemblyScript/assemblyscript/issues/2230 but is a little different ...

With node v16.14.2, I follow the getting started instructions, and am able to successfully build the simple example.

Following that I ...

~~~
npm i as-wasi
~~~

and change the code to ...

~~~
import "wasi"

import {Console} from "as-wasi"
Console.log("Hello World!\n");
~~~

The build now fails as follows:

~~~
% npm run asbuild

> as@1.0.0 asbuild
> npm run asbuild:debug && npm run asbuild:release


> as@1.0.0 asbuild:debug
> asc assembly/index.ts --target debug

ERROR TS6054: File '~lib/as-wasi.ts' not found.

 import {Console} from "as-wasi"
                       ~~~~~~~~~
 in assembly/index.ts(3,23)

FAILURE 1 parse error(s)

> as@1.0.0 asbuild:release
> asc assembly/index.ts --target release

ERROR TS6054: File '~lib/as-wasi.ts' not found.

 import {Console} from "as-wasi"
                       ~~~~~~~~~
 in assembly/index.ts(3,23)

FAILURE 1 parse error(s)
~~~

Rolling back to AS v0.19.x fixes the issue

**Comment by dcodeIO** [comment]
New usage in 0.20 is: `import {Console} from "as-wasi/assembly"`

There is some background in the [release notes](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.20.0). TL;DR is that assuming `./assembly/index.ts` respectively following `ascMain` in `package.json` is not compatible with TS tooling respectively Node leading to all sorts of issues, so it was removed.

**Comment by dcodeIO** [comment]
(also note that using as-wasi for `console.log` is no longer necessary as stdlib implements it already when `import "wasi"` is given)
