### ISSUE TITLE
__allocArray is not a function

### ISSUE THREAD

**Issue by timotheeg** [AssemblyScript/assemblyscript#1433]
Hi there,  I'm just getting started with AssemblyScript for a browser based project, and I hit an early snag with this error:
```
__allocArray is not a function
```

I'm not sure what info I should supply to troubleshoot this, but some details I can think of are below.

in package json (trimmed)
```
  "dependencies": {
    "@assemblyscript/loader": "^0.14.8",
  },
  "devDependencies": {
    "assemblyscript": "^0.14.8",
  },
  "scripts": {
    "asbuild:untouched": "asc assembly/index.ts --target debug --runtime full",
    "asbuild:optimized": "asc assembly/index.ts --target release --runtime full -O3",
    "asbuild": "npm run asbuild:untouched && npm run asbuild:optimized && cp -a build public/ocr",
  },
```

It works ok in my local node 10.16.3:
```bash
> Object.keys(require('./index'))
[ 'memory',
  '__alloc',
  '__retain',
  '__release',
  '__collect',
  '__rtti_base',
  'Uint8ArrayId',
  'Uint8Array2dId',
  'u8ArrayId',
  'u32ArrayId',
  'add',
  'getDigit' ]

> require('./index').__allocArray
[Function: __allocArray]
```

But in the browser (chrome 84.0.4147.105 on OSX), I get:
```bash
Object.keys(module.instance.exports)
(12) ["memory", "__alloc", "__retain", "__release", "__collect", "__rtti_base", "Uint8ArrayId", "Uint8Array2dId", "u8ArrayId", "u32ArrayId", "add", "getDigit"]

module.instance.exports.__allocArray
undefined

module.instance.exports.__allocArray()
Uncaught TypeError: module.instance.exports.__allocArray is not a function
```

I had found [an earlier similar issue](https://github.com/AssemblyScript/assemblyscript/issues/803), which is why I added the `--runtime full` CLI args, but that's still not working. 

Thanks in advance!

**Comment by dcodeIO** [comment]
The `__allocArray` helper becomes injected by the loader

https://github.com/AssemblyScript/assemblyscript/blob/176e932531addee8011b436ac381944841cca48e/lib/loader/index.js#L169-L195

and is not a WebAssembly export like `__alloc`. Generating a project with `asinit` uses the loader automatically. You can get access to `__allocArray` in the browser by utilizing the loader there as well (instead of instantiating with just `WebAssembly.instantiate`). Here's the [loader documentation](https://www.assemblyscript.org/loader.html) in case it helps. Note that the loader is currently a plain old node module, and while it bundles well, using it as-is in the browser currently requires

```html
<script>
var exports = {};
</script>
<script src="path/to/loader.js"></script>
<script>
const loader = exports;
</script>
```

**Comment by timotheeg** [comment]
Thank you @dcodeIO !

**Comment by timotheeg** [comment]
It works! Thanks again :) 

I am working from a webworker, so my code looks like this now (more or less):

```javascript
const exports = {};
importScripts('./loader.js');
const loader = exports;

const loader
    .instantiate(fetch("./build/optimized.wasm"))
    .then(({ exports: asmodule }) => {
    })
```
