### PR TITLE
Strict field initialization

### PR DESCRIPTION
**Pull request by saulecabrera**
This PR addresses #482 

It introduces a new kind of flags: `FieldFlags` in order to track the state of each field per flow. Under the hood, field flags are represented as `Map<string, FieldFlags>` in which each field is uniquely identified by its internal name. Field flags are only initialized when the current flow belongs to a constructor, in every other case they are `null`

A general overview of the changes:

- [x] Dry up error reporting for this case, the code is almost identical when exporting a class and when instantiating one (https://github.com/AssemblyScript/assemblyscript/pull/1154 helps on this)
- [x] Handle conditional field assignment in the constructor
- [x] Handle switch statement
- [x] Fix self compilation errors
- [x] Fix test errors regarding strict initialization
- [x] Constructor inlining

### CODE REVIEW

File: src/compiler.ts [hunk 1]
```diff
@@ -5925,6 +5933,11 @@ export class Compiler extends DiagnosticEmitter {
           );
           return module.unreachable();
         }
+
+        if (flow.actualFunction.is(CommonFlags.CONSTRUCTOR) && !(<Field>target).is(CommonFlags.INITIALIZED)) {
+          (<Field>target).set(CommonFlags.INITIALIZED);
+        }
```
Comment (dcodeIO) [inline src/compiler.ts]: This looks like it needs tracking in flows, so it also covers branches like

```ts
constructor() {
  if (something) this.field = 1;
  // field might still not be initialized
}
```

Comment (saulecabrera) [reply src/compiler.ts]: Definitely, I've marked that as one of the pending items for the PR to be ready for review :) Still wrapping my head around flows.

Comment (MaxGraey) [reply src/compiler.ts]: haha, yeah. "flow" is quite tricky hybrid of cfg & dfg

**Comment by saulecabrera** [comment]
Flows was an interesting journey 😅

I've added support for conditional flows in the constructor in my last commits, in the test files you can find the use cases (https://github.com/AssemblyScript/assemblyscript/pull/1155/files#diff-5fa1688a93849f802b2ae2b7f3cbffe6R26)

I realized that we need the same behaviour for `switch`, I'm tackling that as part of my next commit.

File: src/flow.ts [hunk 2]
```diff
@@ -806,6 +830,20 @@ export class Flow {
         thisLocalFlags[i] = newFlags;
       }
     }
+
+    // Only the most right flow will have an effect
+    // on the resulting flow.
```
Comment (dcodeIO) [inline src/flow.ts]: This seems to miss

```ts
if (cond) {
  // do nothing in left flow
} else {
  this.theField = init; // initialize in right flow
}
```

File: src/flow.ts [hunk 3]
```diff
@@ -519,6 +529,20 @@ export class Flow {
     localFlags[index] = flags & ~flag;
   }
 
+  setFieldFlag(name: string, flag: FieldFlags): void {
+    let fieldFlags = this.fieldFlags;
+    const flags = fieldFlags.get(name) || 0;
```
Comment (dcodeIO) [inline src/flow.ts]: `Map#get` will result in a runtime error if it doesn't contain `name` when compiling to Wasm because the map's value type is non-nullable but the return value would be nullable (`undefined` in JS). Recommended pattern is to use `assert(Map#get(...))` after `Map#has` returned `true`.

File: src/flow.ts [hunk 4]
```diff
@@ -200,6 +206,8 @@ export class Flow {
   scopedLocals: Map<string,Local> | null = null;
   /** Local flags. */
   localFlags: LocalFlags[];
+  /** Field flags. */
+  fieldFlags: Map<string, FieldFlags>;
```
Comment (dcodeIO) [inline src/flow.ts]: Makes me wonder if each field should instead have an incrementing unique id (per class, in layout order) so we can use an array here.

Comment (dcodeIO) [reply src/flow.ts]: Another optimization might be to use a `null` map anywhere but in constructors. Will save quite a bit of memory and reduce GC pressure because there can be quite a lot of flows.

File: src/flow.ts (hunk 2 above)
Comment (saulecabrera) [reply src/flow.ts]: Right, I hadn't correctly verified this, but added a test case for this one: https://github.com/AssemblyScript/assemblyscript/pull/1155/files#diff-5fa1688a93849f802b2ae2b7f3cbffe6R26, it's working as expected.

Also I _think_ it's very similar to: https://github.com/AssemblyScript/assemblyscript/pull/1155/files#diff-5fa1688a93849f802b2ae2b7f3cbffe6R48

File: src/flow.ts (hunk 4 above)
Comment (saulecabrera) [reply src/flow.ts]: > Makes me wonder if each field should instead have an incrementing unique id (per class, in layout order) so we can use an array here.

Right, this makes sense, it was my original approach – similar to what we do with locals –  it's just that I couldn't find a straightforward way to go about it for assignments since I don't have evident access to the field index but I guess we could list fields by index as well. 

I'll try that out!

File: src/flow.ts (hunk 2 above)
Comment (dcodeIO) [reply src/flow.ts]: Hmm, the new test should produce an error, but it doesn't seem to do so. Unless I'm missing something :)

Comment (saulecabrera) [reply src/flow.ts]: I misinterpreted your message, yes, indeed. The field should only be initialiazed in the resulting flow if both flows have initialized it.

File: src/flow.ts [hunk 5]
```diff
@@ -224,7 +224,9 @@ export class Flow {
     flow.returnType = parentFunction.signature.returnType;
     flow.contextualTypeArguments = parentFunction.contextualTypeArguments;
     flow.localFlags = [];
-    flow.fieldFlags = new Map();
+    if (parentFunction.is(CommonFlags.CONSTRUCTOR)) {
```
Comment (dcodeIO) [inline src/flow.ts]: Should be `actualFunction`. Where inlining is performed, for example when inlining a constructor into another function, `parentFunction` is the function being inlined into (hosting all the locals etc), while `actualFunction` is the one becoming inlined (more of an indicator, doesn't hold much state).

File: src/flow.ts [hunk 6]
```diff
@@ -285,7 +287,9 @@ export class Flow {
     branch.localFlags = this.localFlags.slice();
     branch.inlineFunction = this.inlineFunction;
     branch.inlineReturnLabel = this.inlineReturnLabel;
-    branch.fieldFlags = new Map(this.fieldFlags);
+    if (branch.parentFunction.is(CommonFlags.CONSTRUCTOR)) {
```
Comment (dcodeIO) [inline src/flow.ts]: Also `actualFunction`

File: src/flow.ts [hunk 7]
```diff
@@ -831,17 +839,22 @@ export class Flow {
...
 
-    // Only the most right flow will have an effect
-    // on the resulting flow.
-    const rightFieldFlags = right.fieldFlags;
-    const rightKeys = Map_keys(rightFieldFlags);
 
-    for (let _values = Map_values(rightFieldFlags), i = 0, k = _values.length; i < k; ++i) {
-      const rightValue = unchecked(_values[i]);
-      const currentKey = unchecked(rightKeys[i]);
+    if (left.fieldFlags && right.fieldFlags && right.fieldFlags.size > 0) {
```
Comment (dcodeIO) [inline src/flow.ts]: This will currently fail to compile to Wasm because it deals with `object && object && bool`. More of a bug that will be fixed eventually, but explicitly comparing vs `!== null` will work today.

File: src/flow.ts (hunk 5 above)
Comment (saulecabrera) [reply src/flow.ts]: Oh I was just checking this case right now and was wondering what was the difference. I'll change it.

Comment (saulecabrera) [reply src/flow.ts]: Ah also makes sense and that's why we check against `actualFunction` everytime we want to know if we are in the constructor.

File: src/definitions.ts [hunk 8]
```diff
@@ -57,7 +57,7 @@ export abstract class ExportsWalker {
   /** Constructs a new Element walker. */
   constructor(program: Program, includePrivate: bool = false) {
     this.program = program;
-    this.includePrivate;
+    this.includePrivate = includePrivate;
```
Comment (saulecabrera) [inline src/definitions.ts]: @dcodeIO I found out that this was not used, I assume that this was the intended use?

**Comment by saulecabrera** [comment]
In https://github.com/AssemblyScript/assemblyscript/pull/1155/commits/743ef7e89a8999e5f1636607b71a502512af71c4 I fixed self compilation and tests all around. 

Self compilation seems to be OK on CI, anyhow I'm getting an index out of range exception on `npm run astest`, I've tracked this down and I believe it's [here](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/rt.ts#L22), but not sure what is causing it.

File: src/definitions.ts (hunk 8 above)
Comment (dcodeIO) [reply src/definitions.ts]: Whoops, yeah, looks correct now :)

**Comment by MaxGraey** [comment]
It seems main reason on failure happened in `setPedantic`:
https://github.com/AssemblyScript/assemblyscript/runs/544024426#step:6:476

**Comment by dcodeIO** [comment]
Not necessarily, the error begins [a few lines prior](https://github.com/AssemblyScript/assemblyscript/runs/544024426#step:6:431). Wondering how it is even able to print during console.log - as if inspecting would call something.

**Comment by saulecabrera** [comment]
I spent some time today on @MaxGraey's hint (debugging `setPedantic`) but couldn't find anything meaningful, then I started backtracking on all the changes in this PR with no luck, I was mostly trying to prove that all the fields that I marked with `!` have an equivalent effect as prior to this change and that they have nothing to do with the error.

File: src/flow.ts [hunk 9]
```diff
@@ -519,6 +530,26 @@ export class Flow {
...
+  /** Tests if the given field name and flag exist */
+  isFieldFlag(name: string, flag: FieldFlags): bool {
+    const fieldFlags = this.fieldFlags;
+
+    if ((fieldFlags !== null)  && fieldFlags.has(name)) {
+        const flags = assert(fieldFlags.get(name));
+        return (flags & flag) == flag;
+      }
+      return false;
+    }
```
Comment (MaxGraey) [inline src/flow.ts]:
```suggestion
    if (fieldFlags !== null && fieldFlags.has(name)) {
      const flags = assert(fieldFlags.get(name));
      return (flags & flag) == flag;
    }
    return false;
  }
```

File: src/flow.ts [hunk 10]
```diff
@@ -806,6 +837,59 @@ export class Flow {
...
+  /**
+   * Merges the fields flags of the given flows
+   * into the current flow. Flags will only be merged
+   * if both flows definitely define the flags.
+   */
+  mergeFieldFlags(left: Flow, right: Flow): void {
+    if (left.fieldFlags !== null &&
+      right.fieldFlags !== null &&
+      right.fieldFlags.size > 0
+    ) {
```
Comment (MaxGraey) [inline src/flow.ts]:
```suggestion
  mergeFieldFlags(left: Flow, right: Flow): void {
    if (
      left.fieldFlags !== null &&
      right.fieldFlags !== null &&
      right.fieldFlags.size > 0
    ) {
```

File: src/flow.ts [hunk 11]
```diff
@@ -806,6 +837,59 @@ export class Flow {
...
+  /** Inherits the fields flags of the given flow into the current flow */
+  inheritFieldFlags(other: Flow): void {
+    if (
+      this.fieldFlags !== null &&
+      other.fieldFlags !== null
+    ) {
+      const otherFieldFlags = other.fieldFlags;
+      const otherKeys = Map_keys(otherFieldFlags!);
+      const otherValues = Map_values(otherFieldFlags!);
+      const currentFieldFlags = this.fieldFlags;
```
Comment (MaxGraey) [inline src/flow.ts]:
```suggestion
    const currentFieldFlags = this.fieldFlags;
    const otherFieldFlags = other.fieldFlags; 
    if (
      currentFieldFlags !== null &&
      otherFieldFlags !== null
    ) {
      const otherKeys = Map_keys(otherFieldFlags!);
      const otherValues = Map_values(otherFieldFlags!);
```

File: tests/compiler/class.optimized.wat [hunk 12]
```diff
@@ -131,18 +131,6 @@
...
-  local.get $0
-  i32.const 0
-  i32.store offset=4
-  local.get $0
-  i32.const 0
-  i32.store offset=8
-  local.get $0
-  i32.const 0
-  i32.store offset=12
-  local.get $0
```
Comment (MaxGraey) [inline tests/compiler/class.optimized.wat]: It looks pretty suspicious!

File: tests/compiler/resolve-elementaccess.optimized.wat [hunk 13]
```diff
@@ -321,15 +321,6 @@
...
   local.get $0
-  i32.const 0
-  i32.store
-  local.get $0
-  i32.const 0
-  i32.store offset=4
-  local.get $0
-  i32.const 0
-  i32.store offset=8
-  local.get $0
```
Comment (MaxGraey) [inline tests/compiler/resolve-elementaccess.optimized.wat]: Same. @dcodeIO could you check this?

File: tests/compiler/class.optimized.wat (hunk 12 above)
Comment (dcodeIO) [reply tests/compiler/class.optimized.wat]: Looks like that's an inlined `Array` constructor setting `.buffer`, `.dataStart`, `.byteLength` and `.length`, which all are being assigned in the constructor itself. Might be expected if the allocation knows that it does not have to zero-initialize these. Is it?

Comment (saulecabrera) [reply tests/compiler/class.optimized.wat]: Indeed, that's what's happening here, following this reasoning I did a slight change and things seem to be working again, but I could use some clarification from your end.

It seems that even though fields are not definitely initialized at the class level (when calling `makeFieldInitializationInConstructor`) the class expects them to be initialized with their default values.  So in https://github.com/AssemblyScript/assemblyscript/pull/1155/commits/8c6a55440226d0d2364f12d7142a33c9c3965dd5, I don't skip the default init anymore but I don't mark the property as fully initialized unless it complies with the strict property conditions. In my first approach, I was under the impression that skipping the actual default initialization if the field is not compliant was the right thing to do.

Comment (saulecabrera) [reply tests/compiler/class.optimized.wat]: > It seems that even though fields are not definitely initialized at the class level (when calling makeFieldInitializationInConstructor) the class expects them to be initialized with their default values

I'm assuming this makes sense / is required from an allocation perspective and that's why I was hitting the out of range error earlier.

File: src/flow.ts (hunk 10 above)
Comment (MaxGraey) [reply src/flow.ts]: Also plz remove `const leftFieldFlags = left.fieldFlags;` and `const rightFieldFlags = right.fieldFlags;` inside if block later

Comment (MaxGraey) [reply src/flow.ts]: I mean [here](https://github.com/AssemblyScript/assemblyscript/pull/1155/files#diff-8d2c019b40813ce77885d2ad54c2cb15R857) and [here](https://github.com/AssemblyScript/assemblyscript/pull/1155/files#diff-8d2c019b40813ce77885d2ad54c2cb15R861)

Comment (saulecabrera) [reply src/flow.ts]: Right, good catch.

**Comment by saulecabrera** [comment]
So I was not terribly convinced that the fix that I introduced in https://github.com/AssemblyScript/assemblyscript/commit/8c6a55440226d0d2364f12d7142a33c9c3965dd5 was the right way to go without knowing why. I've found the answer, it turns out that [we're not compiling exported generic classes](https://github.com/saulecabrera/assemblyscript/blob/8c6a55440226d0d2364f12d7142a33c9c3965dd5/src/compiler.ts#L816) unless that this is done in a different code path or in a different way that I'm not aware of; that means that with the code that I had prior to https://github.com/AssemblyScript/assemblyscript/commit/8c6a55440226d0d2364f12d7142a33c9c3965dd5 for a class like:

```ts
export class C<T> {
  prop: i32
}
```
won't report any compilation errors and even worse it will skip the initialization of `prop: i32`, this will eventually result in an out of range error.

@dcodeIO:

- Any insight on why we skip the compilation of generic classes?

**Comment by MaxGraey** [comment]
It's well known [issue](https://github.com/AssemblyScript/assemblyscript/issues/570). And we even have PR for this: https://github.com/AssemblyScript/assemblyscript/pull/981

**Comment by dcodeIO** [comment]
What should happen currently is, if one has

```ts
export class C<T> {
  prop: i32
}
```

there is nothing to export because we don't know what `T` will be, so there is no code to export. However, as soon as one does

```ts
export class C<T> {
  prop: i32
}
new C<i32>(); // here
```

we know that there is indeed a class `C<i32>` and we will create the exports for these, but not as `C#xy` but as `C<i32>#xy`, for each concrete class. Might be that this doesn't work a 100% currently, but that's the intended mechanism, with the issue linked above asking for an error if something is exported that is never instantiated.

**Comment by MaxGraey** [comment]
```ts
export class C<T> {
  prop: i32
}
new C<i32>(); // here
```
I guess even with this case we shouldn't export generics for host and throw the error / warning

**Comment by dcodeIO** [comment]
Hesitating a bit here due to all the `someField!` changes to the compiler sources. I think that since we need proper type checking anyway, and can default non-reference fields to zero, perhaps definite assignment should be the default, with the annotation being optional where necessary due to type checking issues with tsc?
