### ISSUE TITLE
The 0.20.0 package distribution looks like broken

### ISSUE THREAD

**Issue by nuxlli** [AssemblyScript/assemblyscript#2230]
I'm following the [Getting started](https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project), and I was able to run `npx asinit .` successfully.

But after that, when I try to run `npx run asbuild:release`, I'm getting this error:

I'm using:

```shell
❯ npm run asbuild:release

> fixture@1.0.0 asbuild:release
> asc assembly/index.ts --target release

file:///Users/evtribeiro/Work/flutter/cli/packages/wasm_interpreter/test/fixture/node_modules/assemblyscript/dist/assemblyscript.js:9
`+new Error().stack},t=function(n,s){if(n==s){if(n!=0)return 0;n=1/n,s=1/s}else{var a=n!=n,o=s!=s;if(a|o)return a-o;n

/// All minified assemblyscript.js content

[];Mr()&&n.push(Ku(r.category)),n.push(Dn(r.category)),Mr()&&n.push(xi),n.push(r.code<1e3?" AS":" TS"),n.push(r.code.toString()),n.push(": "),n.push(r.message);var s=r.range;if(s){let a=s.source;t&&(n.push(`


SyntaxError: missing ) after argument list
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```

Probably `assemblyscript/dist/assemblyscript.js` was builded wrong.

- node: v14.16.1
- npm: 8.3.1
- OS: macOS Big Sur 11.6.5

**Comment by dcodeIO** [comment]
At a glimpse this one looks like a problem with ESM support in Node. Does it work when upgrading to Node 16?

**Comment by togekk1** [comment]
I'm using Node 16 and somehow I got this error in 0.20.0

```
ERROR TS6054: File '~lib/assemblyscript-json.ts' not found.

 import { JSON } from 'assemblyscript-json';
                      ~~~~~~~~~~~~~~~~~~~~~
 in src/assembly/pages/objects.ts(1,22)

FAILURE 1 parse error(s)
ERROR TS6054: File '~lib/assemblyscript-json.ts' not found.

 import { JSON } from 'assemblyscript-json';
                      ~~~~~~~~~~~~~~~~~~~~~
 in src/assembly/i18n/index.ts(1,22)

FAILURE 1 parse error(s)
```

Rolling back to 0.19.23 solved the issue. Is it related?

**Comment by dcodeIO** [comment]
Not related to this particular issue, but related to 0.20 in general. Side-effect of the removal of the `ascMain` field in `package.json` (see release notes).

**Comment by nuxlli** [comment]
> At a glimpse this one looks like a problem with ESM support in Node. Does it work when upgrading to Node 16?

That's it. It was working fine on node v16.6.2.

Obs: I would suggest putting this information on the release changelog. I think it's not clear we need to upgrade to a new node version to keep using AssemblyScript.

**Comment by jonathannorris** [comment]
I'm facing this same issue with my build after upgrading to `0.20.1`, @nuxlli what was the actual solution here that resolved it for you?

**Comment by Mng12345** [comment]
So, this means that i can not use assemblyscript with node version v14?
