### ISSUE TITLE
duplicate identifier with var

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#657]
Looks like there should be a special case for `var`. The following code,

```ts
	describe('.constructor', () => {
		var a = new Quaternion()
		checkQuaternion(a, 0, 0, 0, 1)

		var a = new Quaternion(x, y, z, w)
		checkQuaternion(a, x, y, z, w)
	})
```

gives the error

```
ERROR TS2300: Duplicate identifier 'a'.

                var a = new Quaternion(x, y, z, w)
       ~
 in src/as/glas/math/Quaternion.spec.ts(138,6)
```

Perhaps AS should treat the second `var` as just `a = new Quaternion(x, y, z, w)` as if it didn't have the `var` in front of it, so that it behaves like what people expect in JS? I don't imagine this changes the underlying compiler output.

**Comment by MaxGraey** [comment]
Shadow variable declaration is bad practice even on different scopes, but in same scope this definitely may cause to hidden issues and errors. So just remove `var` for second statment

**Comment by trusktr** [comment]
I agree, and I don't write code that way (I copied this code while porting it to AS).

But non-the-less, I think it's better to match TS/JS as closely as possible, if the goal is to "transpile TypeScript" rather than be a new language.

**Comment by dcodeIO** [comment]
Someone else could argue that enforcing proper `var` placement, which a linter would do otherwise, fits well with a strict subset because it prevents mixing types and other mistakes. Overall I don't have a strong opinion on this one, so maybe let's see what others think as well.

**Comment by trusktr** [comment]
I agree that the current way is actually better, behaving like `let`, which is why `let` was introduced anyway.

**Comment by MaxGraey** [comment]
Personally I vote for banning `var` at all and leave only `let` and `const`

**Comment by trusktr** [comment]
Haha. Well, that'd be nice too! Question is, how true to TypeScript do you want to be?
